### ISSUE TITLE
Hardware info

### ISSUE THREAD

**Issue by iraklis10** [OCVL/IOLM_Parser#1]
Thank you for sharing - sadly the script fails for my PDFs from our IOLMaster - could you please share what version of IOLMaster you have tested it on? 

I tried both
- IOLMaster 700 Version 1.90.12.05
- Carl Zeiss IOLMaster® Advanced Technology V. 7.7 (IOLMaster 500)

Error is thrown after typing in an ID on the prompt:

`Traceback (most recent call last):
  File ".\IO_Master_Parsing.py", line 201, in <module>
    d = c.create(content)
  File ".\IO_Master_Parsing.py", line 154, in create
    row1 = [eDate, r, abstractedContent[0], abstractedContent[2], abstractedContent[3], abstractedContent[6]]
IndexError: list index out of range`

**Comment by Brea24** [comment]
Hello,
Thank you for letting us know. I can add support for the two other IOLMaster document layouts you tried. Would you be able to provide examples of these two document layouts you tried by chance?

**Comment by iraklis10** [comment]
Sure, I am attaching test reports from the former of the two I mentioned above (OD & OS as separate files), Thank you for looking into this. Still curious as to what version your reports are? :-)
[3_22_2022111210Printing Report.pdf](https://github.com/OCVL/IOLM_Parser/files/8323637/3_22_2022111210Printing.Report.pdf)
[3_22_2022111220Printing Report.pdf](https://github.com/OCVL/IOLM_Parser/files/8323638/3_22_2022111220Printing.Report.pdf)

**Comment by Brea24** [comment]
Thank you for providing those example documents, I will work on the support for those. Our reports are from the following device: Carl Zeiss IOLMaster® Advanced Technology V. 5.4.

**Comment by iraklis10** [comment]
Thank you; we have some V. 5.4 PDFs but the majority unfortunately are scanned copies rather than direct, electronic PDF exports and the script fails with a similar error (despite running text recognition beforehand).

**Comment by Eurybiadan** [comment]
Hi- We didn't build in text recognition for scanned copies. However that obviously has a lot of value, so we'll take a look ASAP.

**Comment by Eurybiadan** [comment]
Out of curiosity- which pdf text recognition tool did you use? Was it part of Adobe's software, or something else?

**Comment by iraklis10** [comment]
`Tools > Recognize Text > In this file` within Adobe (Acrobat X Pro). On a similar note, some of our PDFs are redacted (Protection > Mark for redaction) but I don't think this is the issue because I get the same error with unredacted versions.

**Comment by Eurybiadan** [comment]
We can simulate this @Brea24 by printing and scanning back in our existing sheets, and following the above.

**Comment by Eurybiadan** [comment]
Looks like the primary reason we can't load your PDFs is poor pdf support in our current library. (See Issue #2 ) We'll do a refactor and let you know when to give it another shot. Thanks for your patience.

**Comment by Brea24** [comment]
I have added to support for version 7 documents that have all their fields on the summary page filled in. If you have any PDFs that have blank fields on the analyze summary page, I would appreciate it so I can make sure we handle those situations accordingly. 

Let me know of any issues that occur.
